services:
  nginx:
    depends_on:
      wordpress:
        condition: service_healthy
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        - FQDN=${LOGIN}.${DOMAIN_NAME}
        - WEB_ROOT=${WEB_ROOT}
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_files:${WEB_ROOT}
    env_file: .env
    healthcheck:
      test: service nginx status || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception_network
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    env_file: .env
    healthcheck:
      test: /healthcheck.sh
      interval: 2s
      retries: 10
      start_period: 4s
      timeout: 20s
    secrets:
      - db_password
      - db_root_password
    restart: always
  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
      # Bonus
      redis:
        condition: service_started
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        - WEB_ROOT=${WEB_ROOT}
        - WP_VERSION=${WP_VERSION}
        - PHP_VERSION=${PHP_VERSION}
    networks:
      - inception_network
    volumes:
      - wordpress_files:${WEB_ROOT}
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - WORDPRESS_CREDENTIALS_FILE=/run/secrets/credentials
      - FQDN=${LOGIN}.${DOMAIN_NAME}
      # Bonus
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    env_file: .env
    healthcheck:
      test: >
        SCRIPT_FILENAME=/healthcheck.php
        REQUEST_METHOD=GET
        cgi-fcgi -bind -connect wordpress:9000 | grep 'OK' || exit 1
      interval: 4s
      retries: 20
      start_period: 6s
      timeout: 30s
    secrets:
      - db_password
      - credentials
      # Bonus
      - redis_password
    restart: always
  # Bonus
  redis:
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - inception_network
    volumes:
      - redis_dump:/var/lib/redis/
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    healthcheck:
      test: /healthcheck.sh
      interval: 2s
      retries: 10
      start_period: 4s
      timeout: 20s
    secrets:
      - redis_password
    restart: always

networks:
  inception_network:

volumes:
  wordpress_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${LOGIN}/data/wordpress_db
  wordpress_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${LOGIN}/data/wordpress_files
  # Bonus
  redis_dump:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${LOGIN}/data/redis_dump


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  # Bonus
  redis_password:
    file: ../secrets/redis_password.txt