services:
  nginx:
    build:
      context: requirements/nginx
      args:
        - FQDN=${LOGIN}.${DOMAIN_NAME}
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - front_end
    restart: always
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - back_end
    volumes:
      - wordpress_db:/var/lib/mysql
    secrets:
      - db_root_password
    restart: always
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - front_end
      - back_end
    # volumes:
    #   - wordpress:
    # restart: always

networks:
  front_end:
  back_end:

volumes:
 wordpress_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${LOGIN}/data/wordpress_db
#  wordpress:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: /home/${LOGIN}/data/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt