services:
  nginx:
    build:
      context: requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - docker_network
    restart: always
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      secrets:
        - db_root_password
    networks:
      - docker_network
    secrets:
       - db_root_password
    # restart: always

networks:
  docker_network:

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
